[Scheme]
Name=Tashoku
ColorCursor=#eeeeee
ColorForeground=#eeeeee
ColorBackground=#222226
TabActivityColor=#fdb50d
#            Black   Red     Green   Yellow  Blue    Magenta Cyan    White   Br Blac Br Red  Br Gree Br Yell Br Blue Br Mage Br Cyan Br Whit
ColorPalette=#2f2f37;#f74040;#7fc71a;#fdb50d;#1281e2;#c74ce6;#3ecae0;#e0dee8;#50505e;#f46666;#9cdb43;#fdca53;#369ef8;#d474ec;#6dd9e9;#eeeeee
ColorBold=#ffffff
ColorBoldUseDefault=FALSE
